public with sharing class Constants {
    public static final String SUBJECT_EVENT = 'Meeting';
    public static final String WAITING_FOR_APPROVAL_STATUS = 'Waiting for approval';
    public static final String STATUS_APPROVED = 'Approved';
    public static final String STATUS_DENIED = 'Denied';
    public static final String EMAIL_TEMPLATE_WAITING = 'Meeting waiting for approval of the leader';
    public static final String EMAIL_TEMPLATE_APPROVED = 'Meeting is approved by the leader';
    public static final String EMAIL_TEMPLATE_DISAPPROVED = 'Meeting is disapproved by the leader';
    public static final String EMAIL_TEMPLATE_REMOVAL= 'Removal of the meeting';


}