public with sharing class Constants {
    public static final String SUBJECT_EVENT = 'Meeting';
    public static final String WAITING_FOR_APPROVAL_STATUS = 'Waiting for approval';
    public static final String STATUS_APPROVED = 'Approved';
    public static final String STATUS_DENIED = 'Denied';
    public static final String EMAIL_TEMPLATE_WAITING = 'Meeting waiting for approval of the leader';
    public static final String EMAIL_TEMPLATE_APPROVED = 'Meeting is approved by the leader';
    public static final String EMAIL_TEMPLATE_DISAPPROVED = 'Meeting is disapproved by the leader';
    public static final String EMAIL_TEMPLATE_REMOVAL = 'Removal of the meeting';
    public static final String GUEST_USER_NAME = 'Calendar Site Guest User';
    public static final String CONTACT_MANAGER_ID = '0036F000034bameQAA';
    public static final String ACCOUNT_MANAGER_ID = '0016F00003DhHmtQAF';

}